version: '3.7'

volumes:
  postgres:
    name: library-db

services:
  postgres:
    image: postgres
    container_name: library-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data